CompareBazaar/Areas/Admin/Controllers/DashBoardController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CompareBazaar.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using CompareBazaar.Areas.Admin.Models;
using Microsoft.AspNetCore.Http;

namespace CompareBazaar.Areas.Admin.Controllers
{

    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class DashBoardController : Controller
    {



        private readonly ILogger<DashBoardController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;


        public DashBoardController(ILogger<DashBoardController> logger, UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
        }
       
        public ActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PopularProducts()
        {
            return View(await _context.PopularProducts.ToListAsync());
        }

        

        public async Task<IActionResult> DeletePopularProduct(string id)
        {
            var popularProducts = await _context.PopularProducts.FindAsync(id);
            _context.PopularProducts.Remove(popularProducts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

       
        public ActionResult UserList(int id)
        {
            var userlist = _userManager.Users.ToList();
            ViewBag.userlist = userlist;
            return View();
        }

      
        public async Task<ActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            ViewBag.user = user;

            return View();
        }

       
        [HttpPost]
        public async Task<ActionResult> EditUser(string id,IFormCollection userEdit)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                user.FirstName = userEdit["FirstName"];
                user.LastName = userEdit["LastName"];
                user.Email = userEdit["Email"];
                user.UserName = userEdit["Email"];
                user.Address1 = userEdit["Address1"];
                user.Address2 = userEdit["Address2"];
                user.PhoneNumber = userEdit["PhoneNumber"]; ;
                user.PostCode = userEdit["Postcode"];

                var result = await _userManager.UpdateAsync(user);

                if (!result.Succeeded)
                {
                    _logger.LogError("Failed to update User");
                    return RedirectToAction("Error");
                }

                return RedirectToAction("UserList");

            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }
        }

     
        public async Task<ActionResult> DeleteUser(string id)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                var result = await _userManager.DeleteAsync(user);

                if (!result.Succeeded)
                {
                    _logger.LogError("Failed to delete User");
                    return RedirectToAction("Error");
                }

                return RedirectToAction("UserList");
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }

        }

      
        [HttpGet]
        public IActionResult UserAdd()
        {
            return View();
        }

     
        [HttpPost]
        public async Task<ActionResult> UserAdd(IFormCollection collection)
        {
            try
            {
                ApplicationUser user = new ApplicationUser()
                {
                    Email = collection["Email"],
                    UserName = collection["Email"],
                    FirstName = collection["FirstName"],
                    LastName = collection["LastName"]
                };

                var result = await _userManager.CreateAsync(user, collection["Password"]);

                if (!result.Succeeded)
                {
                    _logger.LogError("User creation failed");
                    return RedirectToAction("Error");
                }
                return RedirectToAction("UserList");
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }

        }

        public async Task<IActionResult> ContactList()
        {
            return View(await _context.ContactUs.ToListAsync());
        }


        
        public async Task<IActionResult> DeleteContact(int id)
        {
            var contact = await _context.ContactUs.FindAsync(id);
            _context.ContactUs.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    
    }



}

CompareBazaar/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using CompareBazaar.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <li class="nav-item dropdown me-3 ">
        <a class="nav-link red  " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            <i class="fas fa-user-cog red "></i>
            ADMIN
        </a>
        <ul class="dropdown-menu profilewidth  " aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item ms-3 fs-5 dropdownbg text-black dropdownbgprofilecolor" href="https://comparebazaar-api.herokuapp.com/admin " target="_blank">API Admin Panel</a></li>
            <li> <hr class="dropdown-divider"></li>
            <li><a class="dropdown-item ms-3 fs-5 dropdownbg text-black dropdownbgprofilecolor " asp-area="Admin" asp-controller="DashBoard" asp-action="" target="_blank">Site Admin Panel</a></li>

        </ul>
    </li>
}

CompareBazaar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->

    <title>@ViewData["Title"] - Compare Bazaar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/User/lib/bootstrap/dist/css/cssfile.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/User/lib/bootstrap/dist/fontawesome-free-6.0.0-web/css/all.css">

   <!-- <script src="https://kit.fontawesome.com/0ee938b2d7.js" crossorigin="anonymous"></script>-->
    @*<script src="~/User/lib/bootstrap/dist/css/js/comparebazzar.js" crossorigin="anonymous"></script>*@
</head>

<body>
    @if (ViewBag.HideNavBar == null)
    {
        <nav class="navbar navbar-expand-lg navbar-light sticky-top bg-light py-2 navbar1">
            <div class="container-fluid">
                <a class="navbar-brand ms-1 fs-2 wbnamesize " asp-action="">
                    <img src="~/User/images/logoo.png"
                         alt="CompareBazzar Logo" width="70" class="wbimg img-fluid">
                    COMPARE<b>BAZAAR</b>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav  mb-2 mb-lg-0  ms-auto me-4 fs-5">
                        <partial name="_AdminMenuPartial" />
                        <li class="nav-item dropdown me-3">
                            <!-- <a class="nav-link red "   href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false"><i class="fas fa-user-alt red "> </i>PROFILE</a> -->
                            <a class="nav-link red  " href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-user red"></i>
                                PROFILE
                            </a>
                            <partial name="_LoginPartial" />

                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link  red " aria-current="page" asp-action="WishList">
                                <i class="fas fa-heart red "></i>
                                WISHLIST
                            </a>
                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link  red " aria-current="page" asp-controller="Home" asp-action="CompareChart">
                                <i class="fas fa-balance-scale-left red"></i>
                                COMPARE CHART
                            </a>
                        </li>
                        <!-- <li class="nav-item me-3">
                         <a class="nav-link red " href="#"><i class="fas fa-shopping-cart  red"></i> CART</a>
                        </li>  -->
                    </ul>
                </div>
            </div>
        </nav>


       
    }
    @RenderBody()

    @if (ViewBag.HideNavBar == null)
    {
        <footer class="bg-black ">
            <div class="container mt-5 py-5">
                <div class="row ">
                    <div class="d-flex  flex-column col-sm-12 col-lg-3 col-12 mb-5 position-relative top-0 start-0">
                        <h6 class="text-white fs-3  ">COMPARE<b>BAZAAR</b></h6>
                    </div>
                    <div class="d-flex flex-column col-sm-12 col-lg-3 col-12 mb-5 py-4">
                        <h6 class="text-white mb-4">QUICK MENU</h6>
                        <ul class="list-unstyled">
                            <li>
                                <a class="text-decoration-none text-muted footercolor" asp-controller="" asp-action="About">
                                    About
                                    COMPAREBAZAAR
                                </a>
                            </li>
                            <li><a class="text-decoration-none text-muted footercolor " asp-controller="" asp-action="CompareChart">Compare Products</a></li>
                            <li><a class="text-decoration-none text-muted footercolor"  asp-controller="" asp-action="Contact">Contact Us</a></li>
                            <li><a class="text-decoration-none text-muted footercolor"  asp-controller="" asp-action="FAQs">FAQs</a></li>
                            <li><a class="text-decoration-none text-muted footercolor" asp-action="TAndC">Terms & Conditions</a></li>
                        </ul>
                    </div>
                    <div class="d-flex flex-column col-sm-12 col-lg-3 col-12 mb-5 py-4 ">
                        <h6 class="text-white mb-4">CATEGORIES</h6>
                        <ul class="list-unstyled">
                            <li><a class="text-decoration-none  text-muted footercolor" asp-controller="Home" asp-action="ProductsList">Mobiles</a></li>
                            <li><a class="text-decoration-none text-muted footercolor" asp-controller="Home" asp-action=""> Tablets</a></li>
                            <li><a class="text-decoration-none text-muted  footercolor" asp-controller="Home" asp-action="">Laptops</a></li>
                            <li><a class="text-decoration-none text-muted footercolor" asp-controller="Home" asp-action="">Computers</a></li>
                            <li><a class="text-decoration-none text-muted footercolor" asp-controller="Home" asp-action="">TVs</a></li>
                            <li><a class="text-decoration-none text-muted footercolor" asp-controller="Home" asp-action="">Electronices</a></li>
                            <li><a class="text-decoration-none text-muted  footercolor" asp-controller="Home" asp-action="">Appliances</a></li>
                        </ul>
                    </div>
                    <div class="d-flex flex-column col-sm-12 col-lg-3 col-12 mb-5 py-4 ">
                        <h6 class="text-white mb-4">CONNECT WITH US ON</h6>
                        <div class="flew-row">
                            <i class="fab fa-facebook-f  me-4 fs-5 footercolor"></i>
                            <i class="fab fa-twitter  me-4 fs-5 footercolor "></i>
                            <i class="fab fa-instagram  me-4 fs-5 footercolor "></i>
                            <i class="fab fa-whatsapp  me-4 fs-5 footercolor "></i>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    }
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
                integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
                crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
                integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
                crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <script>
            $('#owl-carousel1').owlCarousel({
                loop: false,
                margin: 10,
                nav: false,
                dots: false,

                responsive: {
                    200: {
                        items: 2
                    },
                    300: {
                        items: 3
                    },
                    400: {
                        items: 4
                    },
                    500: {
                        items: 5
                    },
                    600: {
                        items: 6
                    },

                    900: {
                        items: 7
                    },
                    1000: {
                        items: 8
                    },

                    1100: {
                        items: 9
                    },
                    1200: {
                        items: 10
                    },
                    1300: {
                        items: 11
                    },
                    1400: {
                        items: 12
                    }
                }
            })
            $('#owl-carousel2').owlCarousel({
                loop: true,
                margin: 15,
                nav: false,
                autoplay: true,
                autoplayTimeout: 2000,
                responsive: {

                    0: {
                        items: 1
                    },
                    500:{
                        items:2
                    },
                    900: {
                        items: 2
                    },
                    1000: {
                        items: 2
                    },
                    1300: {
                        items: 3
                    },
                    1400: {
                        items: 5
                    }
                }
            })

           
            //function Wishlist(wishlist) {
            //    if (sessionStorage.getItem('class')) {
            //       wishlist.className = sessionStorage.getItem('class');
            //    } else {
            //        wishlist.className='text-red';
            //        sessionStorage.setItem('class', 'text-red');
            //    }
            //}
            function Wishlist(wishlist) {
                if (wishlist.className != 'text-black')
                {
                    wishlist.className = 'text-black';
                }
                else {
                    wishlist.className = 'text-red';
                }
            }

        </script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>